### ISSUE TITLE
Reset the measure to zero when tapping on the number

### ISSUE THREAD

**Issue by ericzolf** [mobeil1/GuessIron#4]
It's a trifle but I find it annoying to not have a reset button to bring back the measure to 0. No practical implication, I know, but somehow disturbing. I'd suggest to reset the measure to 0 when tapping on it.

**Comment by mobeil1** [comment]
good idea. i will think about it.

**Comment by SodaWithoutSparkles** [comment]
Did you mean:

- the scale should return to 0 end
- set the current reading to 0 to measure relative position (i.e. negative distance exist)

**Comment by ericzolf** [comment]
the scale should return to 0 end, no "selection" visible anymore.

**Comment by mobeil1** [comment]
function of the button can be configured in v5.0
