### ISSUE TITLE
Tapping and dragging produce different values 

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [mobeil1/GuessIron#6]
In normal mode, dragging the scale produce a reading w/o margins applied, but tapping does. 

When screen margin mode is enabled, we dont have this problem.

**Comment by SodaWithoutSparkles** [comment]
https://github.com/mobeil1/GuessIron/assets/64138578/1c87982c-076c-4d9b-b4ad-6fe9811faaf6

**Comment by mobeil1** [comment]
will resolve this. thx

**Comment by mobeil1** [comment]
fixed in v5.0
